export const POPULATE_DIRECTORY_BEGIN = 'POPULATE_DIRECTORY_BEGIN';
export const POPULATE_DIRECTORY_SUCCESS = 'POPULATE_DIRECTORY_SUCCESS';
export const POPULATE_DIRECTORY_FAILURE = 'POPULATE_DIRECTORY_FAILURE';
export const POPULATE_DETAILS_BEGIN = 'POPULATE_DETAILS_BEGIN';
export const POPULATE_DETAILS_SUCCESS = 'POPULATE_DETAILS_SUCCESS';
export const POPULATE_DETAILS_FAILURE = 'POPULATE_DETAILS_FAILURE';