export const POPULATE_DIRECTORY_BEGIN = 'POPULATE_DIRECTORY_BEGIN';
export const POPULATE_DIRECTORY_SUCCESS = 'POPULATE_DIRECTORY_SUCCESS';
export const POPULATE_DIRECTORY_FAILURE = 'POPULATE_DIRECTORY_FAILURE';
